import React from 'react'



const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
      
        {children}
      </body>
    </html>
  );
}

export { metadata };
